name: Prettier CI
on: [push, pull_request]
jobs:
  format:
    # Check if the PR is not from a fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: prettier
        run: npx prettier . --write
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Prettified!"
          git push
